# Dirty Trick for creating and setting up password for new users

---
- hosts: [hosts]
  tasks:
  - name: Create Multiple UserID on Test Env
    user:
      name: "{{ item.names }}"
      uid: "{{ item.uid }}"
      group: "{{ item.pgroup }}"
  - name: Generate Default Password
    shell: echo -e "booyahpw\nbooyahpw" | sudo passwd "{{ item.names }}"
    with_items:
      - { names: $1, uid: $2, pgroup: $3 }
