# Dirty tricks for creating Home and SSh folder for Active Directory users
#

- hosts: all
  tasks:
  - name: Get List of Active Directory Users
    shell: adquery user -n > /tmp/adusers.txt
  - name: Create Active Directory Users Home Directory
    shell: for user in `cat /tmp/adusers.txt`; do sudo su -l $user; done

- hosts: [metadata master host]
  tasks:
  - name: Generate SSH Key
    shell: for user in `cat /tmp/adusers.txt`; do sudo su $user -c "cd ~ | whoami | echo -e 'y\n' | ssh-keygen -t rsa -q -f ~/.ssh/id_rsa -N ''"; done
  - name: Generate Authorized Keys
    shell: for user in `cat /tmp/adusers.txt`; do sudo su $user -c "cd ~ | whoami | cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys"; done
  - name: Temp location for Active Directory Users Home
    shell: for user in `cat /tmp/adusers.txt`; do sudo cp -pr /home/$user /<NFSMOUNTED FILESYSSTEM>/tmp/; done

- hosts: all
  tasks:
   - name: Propagate Passwordless SSH Key to Other Servers
     shell: for user in `cat /tmp/adusers.txt`; do sudo cp -pr /<NFSMOUNTED FILESYSSTEM>/tmp/$user/.ssh /home/$user; done
